<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            // Cursos Gratuitos
            [
                'title' => 'Programación en C desde Cero',
                'description' => 'Aprende C desde los fundamentos: sintaxis, variables, funciones, punteros, memoria dinámica y estructuras de datos. Perfecto para entender los fundamentos de la programación.',
                'category' => 'programming',
                'level' => 'beginner',
                'type' => 'free',
                'duration' => '6 semanas',
                'instructor' => null,
                'lessons' => ['Introducción a C', 'Tipos de Datos y Variables', 'Estructuras de Control', 'Funciones', 'Punteros', 'Memoria Dinámica', 'Estructuras de Datos', 'Proyecto Final'],
                'price' => 0.00,
                'image_url' => null,
                'requirements' => 'No se requieren conocimientos previos de programación',
                'what_you_will_learn' => 'Dominar C, entender punteros, gestión de memoria, algoritmos fundamentales, y crear programas eficientes desde cero.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],
            [
                'title' => 'C++ Moderno y Orientado a Objetos',
                'description' => 'Domina C++ con programación orientada a objetos, STL, templates, y las características modernas de C++11/14/17. Aprende a crear software eficiente y mantenible.',
                'category' => 'programming',
                'level' => 'intermediate',
                'type' => 'free',
                'duration' => '8 semanas',
                'instructor' => null,
                'lessons' => ['Fundamentos de C++', 'POO: Clases y Objetos', 'Herencia y Polimorfismo', 'Templates y STL', 'Memoria y RAII', 'Smart Pointers', 'Lambdas y C++ Moderno', 'Proyecto Completo'],
                'price' => 0.00,
                'image_url' => null,
                'requirements' => 'Conocimientos básicos de programación o haber completado el curso de C',
                'what_you_will_learn' => 'Diseñar software con POO, usar STL eficientemente, dominar templates, gestionar memoria, y aplicar las mejores prácticas de C++ moderno.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],
            [
                'title' => 'Desarrollo con C# y .NET',
                'description' => 'Aprende C# para crear aplicaciones de escritorio, web y móviles con .NET. Cubriremos desde lo básico hasta técnicas avanzadas de desarrollo empresarial.',
                'category' => 'programming',
                'level' => 'beginner',
                'type' => 'free',
                'duration' => '7 semanas',
                'instructor' => null,
                'lessons' => ['Introducción a C#', 'POO en C#', 'Colecciones y LINQ', 'Excepciones y Depuración', 'Interfaces y Delegados', 'Tasks y Async/Await', 'Entity Framework', 'Proyecto .NET'],
                'price' => 0.00,
                'image_url' => null,
                'requirements' => 'Conocimientos básicos de programación',
                'what_you_will_learn' => 'Crear aplicaciones .NET, usar LINQ, programación asíncrona, trabajar con bases de datos, y desarrollar software empresarial con C#.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],
            [
                'title' => 'JavaScript desde Cero',
                'description' => 'Aprende JavaScript desde los fundamentos: variables, funciones, objetos, arrays, DOM manipulation, y programación asíncrona. El lenguaje más popular del desarrollo web.',
                'category' => 'frontend',
                'level' => 'beginner',
                'type' => 'free',
                'duration' => '5 semanas',
                'instructor' => null,
                'lessons' => ['Introducción a JavaScript', 'Variables y Tipos de Datos', 'Funciones y Scope', 'Objetos y Arrays', 'DOM y Eventos', 'Async/Await y Promises', 'ES6+ Features', 'Proyecto To-Do App'],
                'price' => 0.00,
                'image_url' => null,
                'requirements' => 'Conocimientos básicos de HTML y CSS',
                'what_you_will_learn' => 'Dominar JavaScript moderno, manipular el DOM, trabajar con APIs, programación asíncrona, y crear aplicaciones interactivas.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],
            [
                'title' => 'Python para Principiantes',
                'description' => 'Aprende Python desde cero: sintaxis simple, estructuras de datos, funciones, módulos, y programación orientada a objetos. Ideal para empezar en programación.',
                'category' => 'programming',
                'level' => 'beginner',
                'type' => 'free',
                'duration' => '6 semanas',
                'instructor' => null,
                'lessons' => ['Introducción a Python', 'Tipos de Datos y Variables', 'Estructuras de Control', 'Listas y Diccionarios', 'Funciones y Módulos', 'POO en Python', 'Manejo de Archivos', 'Proyecto Final'],
                'price' => 0.00,
                'image_url' => null,
                'requirements' => 'No se requieren conocimientos previos de programación',
                'what_you_will_learn' => 'Dominar Python, trabajar con estructuras de datos, crear funciones reutilizables, programación orientada a objetos, y desarrollar proyectos prácticos.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],
            [
                'title' => 'HTML y CSS Fundamentos',
                'description' => 'Aprende a crear páginas web desde cero con HTML5 y CSS3. Diseño responsive, flexbox, grid, animaciones, y mejores prácticas de desarrollo web moderno.',
                'category' => 'frontend',
                'level' => 'beginner',
                'type' => 'free',
                'duration' => '4 semanas',
                'instructor' => null,
                'lessons' => ['HTML5 Semántico', 'CSS Básico y Selectores', 'Flexbox y Layout', 'CSS Grid', 'Responsive Design', 'Animaciones y Transiciones', 'Bootstrap y Frameworks', 'Proyecto Landing Page'],
                'price' => 0.00,
                'image_url' => null,
                'requirements' => 'No se requieren conocimientos previos',
                'what_you_will_learn' => 'Crear páginas web modernas, diseño responsive, usar Flexbox y Grid, animaciones CSS, y aplicar mejores prácticas de desarrollo web.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],

            // Cursos Premium
            [
                'title' => 'Spring Boot Avanzado',
                'description' => 'Construye aplicaciones backend robustas y escalables con Spring Boot. Aprende microservicios, seguridad, testing, y despliegue en producción.',
                'category' => 'backend',
                'level' => 'advanced',
                'type' => 'premium',
                'duration' => '10 semanas',
                'instructor' => null,
                'lessons' => ['Spring Boot Fundamentals', 'Spring Data JPA', 'Spring Security', 'REST APIs Avanzadas', 'Testing con JUnit y Mockito', 'Microservicios', 'Docker y Deployment', 'Monitoring y Observabilidad', 'Proyecto Empresarial'],
                'price' => 2.99,
                'image_url' => null,
                'requirements' => 'Conocimientos de Java y programación orientada a objetos',
                'what_you_will_learn' => 'Crear backends escalables con Spring Boot, implementar seguridad, testing profesional, microservicios, y desplegar en producción.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],
            [
                'title' => 'React Avanzado: Desarrollo Profesional',
                'description' => 'Domina React con hooks modernos, context API, performance optimization, testing, y arquitecturas escalables. Crea aplicaciones de nivel profesional.',
                'category' => 'frontend',
                'level' => 'advanced',
                'type' => 'premium',
                'duration' => '9 semanas',
                'instructor' => null,
                'lessons' => ['Hooks Avanzados', 'Context API y Estado Global', 'React Router Avanzado', 'Performance Optimization', 'Testing con Jest y RTL', 'Custom Hooks', 'Arquitectura de Componentes', 'Next.js y SSR', 'Proyecto Portfolio'],
                'price' => 2.99,
                'image_url' => null,
                'requirements' => 'Conocimientos de JavaScript ES6+, HTML y CSS',
                'what_you_will_learn' => 'Dominar React moderno, optimizar performance, testing profesional, arquitecturas escalables, y crear aplicaciones production-ready.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],
            [
                'title' => 'Node.js y Express: Backend Profesional',
                'description' => 'Construye APIs RESTful robustas y escalables con Node.js y Express. Aprende autenticación JWT, bases de datos, testing, y despliegue en producción con las mejores prácticas.',
                'category' => 'backend',
                'level' => 'advanced',
                'type' => 'premium',
                'duration' => '10 semanas',
                'instructor' => null,
                'lessons' => ['Node.js Fundamentals', 'Express.js y Middleware', 'RESTful APIs', 'Autenticación JWT', 'MongoDB y Mongoose', 'PostgreSQL con Sequelize', 'Testing con Jest y Supertest', 'WebSockets y Real-time', 'Docker y Deployment', 'Proyecto E-commerce API'],
                'price' => 2.99,
                'image_url' => null,
                'requirements' => 'Conocimientos sólidos de JavaScript, HTML y CSS',
                'what_you_will_learn' => 'Crear APIs RESTful profesionales, implementar autenticación segura, trabajar con bases de datos, testing completo, y desplegar aplicaciones en producción.',
                'enrollments_count' => 0,
                'rating' => 0,
                'ratings_count' => 0,
                'is_active' => true,
            ],
        ];

        foreach ($courses as $course) {
            Course::updateOrCreate(
                ['title' => $course['title']],
                $course
            );
        }
    }
}
